# ----------------------------------------------------------------------------- 
# Defaults
# -----------------------------------------------------------------------------
defaults:
  # pages 기본 layout
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  # assets 제외 (사이트맵 등)
  - scope:
      path: "assets"
    values:
      sitemap: false

# ----------------------------------------------------------------------------- 
# Site settings
# -----------------------------------------------------------------------------
url: "https://arsine00.github.io"
baseurl: ""
title: Kim Kihyun
name: Kim Kihyun
email: sklnk@postech.ac.kr
description: "Short bio / tagline"
keywords: kihyun-kim, postech, university-of-tokyo, academic-portfolio
lang: en
icon: ⚛️

last_updated: false
impressum_path:
back_to_top: true

# ----------------------------------------------------------------------------- 
# Theme
# -----------------------------------------------------------------------------
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed

# ----------------------------------------------------------------------------- 
# Layout & Navbar
# -----------------------------------------------------------------------------
navbar_fixed: true
footer_fixed: true
search_enabled: true
socials_in_search: true
posts_in_search: true
bib_search: true
max_width: 930px

# ----------------------------------------------------------------------------- 
# Open Graph & Schema.org
# -----------------------------------------------------------------------------
serve_og_meta: false
serve_schema_org: false
og_image:

# ----------------------------------------------------------------------------- 
# Analytics & Verification
# -----------------------------------------------------------------------------
google_analytics:
cronitor_analytics:
pirsch_analytics:
openpanel_analytics:
google_site_verification:
bing_site_verification:

# ----------------------------------------------------------------------------- 
# Blog
# -----------------------------------------------------------------------------
blog_name: al-folio
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/
lsi: false
pagination:
  enabled: true
related_blog_posts:
  enabled: true
  max_related: 5

giscus:
  repo:
  repo_id:
  category: Comments
  category_id:
  mapping: title
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  dark_theme: dark
  light_theme: light
  emit_metadata: 0
  lang: en

disqus_shortname: al-folio

external_sources:
  - name: medium.com
    rss_url: https://medium.com/@al-folio/feed
  - name: Google Blog
    posts:
      - url: https://blog.google/technology/ai/google-gemini-update-flash-ai-assistant-io-2024/
        published_date: 2024-05-14

# ----------------------------------------------------------------------------- 
# Newsletter
# -----------------------------------------------------------------------------
newsletter:
  enabled: false
  endpoint:

# ----------------------------------------------------------------------------- 
# Collections
# -----------------------------------------------------------------------------
collections:
  books:
    output: true
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true

# ----------------------------------------------------------------------------- 
# Jekyll settings
# -----------------------------------------------------------------------------
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
keep_files:
  - CNAME
  - .nojekyll

plugins:
  - jekyll-archives-v2
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
